# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32863988744aebfb067d0d53ffe09acfcd38eadf5e1e83f8416e56395968e8755cb36fbb367c63dd4b06c1b292e1e31bf0a3eea1938f07d42d6978f71b3a5468

test:
  secret_key_base: 5612b7c4e99dc6ae8c43355b80c088374b9dcbbc3f74421b4b24e4f08822a0d40fc27dd905349f86d21a31d3e31b051417f820813bcea91b3cc4482898f69a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
